version: "3.5"

networks:
  cheepnet:
    name: cheapnet

    ipam:
      driver: default
      config:
        - subnet: 12.12.12.0/28

services:
  www:
    container_name: www.cheepnet.com
    build:
      context: .
      dockerfile: www.dockerfile

    ports:
      - "80:80"
      - "8080:8080"
    
    networks:
      cheepnet:
    
    depends_on:
      - cache
    
    env_file:
      - .env
      
    command: node index.js
  
  cache:
    image: redis:latest
    container_name: cache.cheepnet.com

    networks:
      cheepnet:
    
    ports:
      - "6379:6379"
    